### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by helloaziz** [lngthnhan/MSI-GF63-BigSur#1]
can u share the EFI folder?

**Comment by lngthnhan** [comment]
Updated it, no idea how to fix audio so fix yourself :v

**Comment by helloaziz** [comment]
> Updated it, no idea how to fix audio so fix yourself :v

fan working properly? I have a problem, fans works so slow, I mean basically doesnt work and what can I do for fix that? I tried using MSIFanControl kext but nothing.

**Comment by lngthnhan** [comment]
You can't use the nvidia graphics card so the fan is not a problem since you don't use the dedicated graphics card, I guess

**Comment by helloaziz** [comment]
> You can't use the nvidia graphics card so the fan is not a problem since you don't use the dedicated graphics card, I guess

i'm already disable the discrete gpu, but still my device get burn, can u share a screenshot of your device while running intel power gadget?

**Comment by lngthnhan** [comment]
I don't have one since I already removed this shitty hackintosh stuff, it messes up Windows and my work. But basically its fine with Final Cut Pro, Photoshop or even game like CSGO

**Comment by helloaziz** [comment]
> I don't have one since I already removed this shitty hackintosh stuff, it messes up Windows and my work. But basically its fine with Final Cut Pro, Photoshop or even game like CSGO

one more thing, did the webcam working perfectly like in windows?

**Comment by lngthnhan** [comment]
At first my EFI worked perfectly except AirDrop/Handoff since it needs native Mac card. But I did something and messed up audio, everything works fine

**Comment by helloaziz** [comment]
> At first my EFI worked perfectly except AirDrop/Handoff since it needs native Mac card. But I did something and messed up audio, everything works fine

ok thank
